### PR TITLE
[FW] c1

### PR DESCRIPTION
**Pull request by xmo-odoo**
Forward-Port-Of: odoo-mergebot-testing-org/ignore_proj_IBo-GXAO#1

### CODE REVIEW

**Comment by xmo-odoo** [comment]
[Pull request status dashboard](http://localhost:8069/odoo-mergebot-testing-org/ignore_proj_IBo-GXAO/pull/2).

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer cherrypicking of pull request odoo-mergebot-testing-org/ignore_proj_IBo-GXAO#1 failed.

* d5c3375326b737844ebd91028397b8599364cd63 <- on this commit
* 11ef8533901fc5c4b87f48deb4a7b5aad5cfcb14

stdout:
```
Auto-merging g
CONFLICT (add/add): Merge conflict in g

```

stderr:
```
07:46:05.534219 git.c:460               trace: built-in: git cherry-pick d5c3375326b737844ebd91028397b8599364cd63
error: could not apply d5c3375... c0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by odoomergebotsacrifice-reviewer** [comment]
hansen r+

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer unable to stage: All commits must have author and committer email, missing email on 145f4e800645fae85bd0c683e7bb62b878cfbed9 indicates the authorship is most likely incorrect.

**Pull request closed without merging**
